version: '3.9'
services:
  app:
    image: python:3.11
    working_dir: /app/src/example_service
    command: sh -c "pip install -r requirements.txt && python manage.py runserver 0.0.0.0:8000"
    volumes:
      - ../..:/app
    ports:
      - "8000:8000"
    environment:
      KEYCLOAK_SERVER_URL: http://localhost:8080/
      KEYCLOAK_REALM: demo
      KEYCLOAK_CLIENT_ID: demo-client
      KEYCLOAK_CLIENT_SECRET: demo-secret
